export const ITEM_CATEGORY_MAP: Record<string, string> = {
  // ─── Carnes ───
  "alcatra": "Carnes",
  "contrafile": "Carnes",
  "filemignon": "Carnes",
  "picanha": "Carnes",
  "maminha": "Carnes",
  "fraldinha": "Carnes",
  "coxaomole": "Carnes",
  "coxaoduro": "Carnes",
  "patinho": "Carnes",
  "lagarto": "Carnes",
  "musculo": "Carnes",
  "costelabovina": "Carnes",
  "carnemoidaacem": "Carnes",
  "bucho": "Carnes",
  "linguabovina": "Carnes",
  "figadobovina": "Carnes",
  "coracaobovina": "Carnes",
  "lombosuino": "Carnes",
  "pernilsuino": "Carnes",
  "costelasuina": "Carnes",
  "bistecasuina": "Carnes",
  "linguicatoscana": "Carnes",
  "linguicacalabresa": "Carnes",
  "bacon": "Carnes",
  "presuntocozido": "Carnes",
  "salame": "Carnes",
  "peitodeperudefumado": "Carnes",
  "carne": "Carnes",
  "bife": "Carnes",
  "presunto": "Carnes",
  "salsicha": "Carnes",

  // ─── Aves ───
  "peitodefrango": "Aves",
  "coxadefrango": "Aves",
  "sobrecoxadefrango": "Aves",
  "asadefrango": "Aves",
  "frangointeiro": "Aves",
  "coracaodefrango": "Aves",
  "filedepeitodeperu": "Aves",
  "chesterinteiro": "Aves",
  "patointeiro": "Aves",
  "frangodesfiado": "Aves",
  "frango": "Aves",

  // ─── Peixes e Frutos do Mar ───
  "salmaofresco": "Peixes e Frutos do Mar",
  "tilapiafile": "Peixes e Frutos do Mar",
  "merluzafile": "Peixes e Frutos do Mar",
  "bacalhaudessalgado": "Peixes e Frutos do Mar",
  "bacalhausalgado": "Peixes e Frutos do Mar",
  "sardinhafresca": "Peixes e Frutos do Mar",
  "atumfresco": "Peixes e Frutos do Mar",
  "camaraodescascado": "Peixes e Frutos do Mar",
  "camaraocomcasca": "Peixes e Frutos do Mar",
  "lulalimpa": "Peixes e Frutos do Mar",
  "polvo": "Peixes e Frutos do Mar",
  "mexilhao": "Peixes e Frutos do Mar",
  "vongole": "Peixes e Frutos do Mar",
  "ostra": "Peixes e Frutos do Mar",
  "lagosta": "Peixes e Frutos do Mar",
  "peixe": "Peixes e Frutos do Mar",

  // ─── Frios e Laticínios ───
  "queijomussarela": "Frios e Laticínios",
  "queijoprato": "Frios e Laticínios",
  "queijominasfrescal": "Frios e Laticínios",
  "queijoparmesaoralado": "Frios e Laticínios",
  "queijogorgonzola": "Frios e Laticínios",
  "queijoprovolone": "Frios e Laticínios",
  "queijoricota": "Frios e Laticínios",
  "requeijao": "Frios e Laticínios",
  "creamcheese": "Frios e Laticínios",
  "manteigacomsal": "Frios e Laticínios",
  "manteigasemsal": "Frios e Laticínios",
  "margarina": "Frios e Laticínios",
  "leiteintegral": "Frios e Laticínios",
  "leitedesnatado": "Frios e Laticínios",
  "cremedeleitecaixa": "Frios e Laticínios",
  "leitecondensado": "Frios e Laticínios",
  "iogurtenatural": "Frios e Laticínios",
  "iogurtegrego": "Frios e Laticínios",
  "nata": "Frios e Laticínios",
  "leiteempo": "Frios e Laticínios",
  "leite": "Frios e Laticínios",
  "manteiga": "Frios e Laticínios",
  "queijo": "Frios e Laticínios",
  "iogurte": "Frios e Laticínios",
  "cremedeleite": "Frios e Laticínios",

  // ─── Ovos ───
  "ovo": "Ovos",
  "ovos": "Ovos",
  "ovosdecodorna": "Ovos",
  "ovoscaipira": "Ovos",
  "ovosbrancos": "Ovos",
  "ovosmarrom": "Ovos",
  "clarasdeovo": "Ovos",
  "gemasdeovo": "Ovos",

  // ─── Hortifrúti — Verduras e Legumes ───
  "alfacecrespa": "Hortifrúti — Verduras e Legumes",
  "alfaceamericana": "Hortifrúti — Verduras e Legumes",
  "alfaceroxa": "Hortifrúti — Verduras e Legumes",
  "rucula": "Hortifrúti — Verduras e Legumes",
  "agriao": "Hortifrúti — Verduras e Legumes",
  "espinafre": "Hortifrúti — Verduras e Legumes",
  "couve": "Hortifrúti — Verduras e Legumes",
  "repolhoverde": "Hortifrúti — Verduras e Legumes",
  "repolhoroxo": "Hortifrúti — Verduras e Legumes",
  "brocolis": "Hortifrúti — Verduras e Legumes",
  "couveflor": "Hortifrúti — Verduras e Legumes",
  "tomate": "Hortifrúti — Verduras e Legumes",
  "tomatecereja": "Hortifrúti — Verduras e Legumes",
  "cebolabranca": "Hortifrúti — Verduras e Legumes",
  "cebolaroxa": "Hortifrúti — Verduras e Legumes",
  "cebolinhaverde": "Hortifrúti — Verduras e Legumes",
  "pimentaoverde": "Hortifrúti — Verduras e Legumes",
  "pimentaovermelho": "Hortifrúti — Verduras e Legumes",
  "pimentaoamarelo": "Hortifrúti — Verduras e Legumes",
  "batatainglesa": "Hortifrúti — Verduras e Legumes",
  "batatadoce": "Hortifrúti — Verduras e Legumes",
  "mandiocaaipim": "Hortifrúti — Verduras e Legumes",
  "inhame": "Hortifrúti — Verduras e Legumes",
  "cenoura": "Hortifrúti — Verduras e Legumes",
  "beterraba": "Hortifrúti — Verduras e Legumes",
  "chuchu": "Hortifrúti — Verduras e Legumes",
  "abobrinha": "Hortifrúti — Verduras e Legumes",
  "berinjela": "Hortifrúti — Verduras e Legumes",
  "abobora": "Hortifrúti — Verduras e Legumes",
  "pepino": "Hortifrúti — Verduras e Legumes",
  "alho": "Hortifrúti — Verduras e Legumes",
  "alhoporo": "Hortifrúti — Verduras e Legumes",
  "salsao": "Hortifrúti — Verduras e Legumes",
  "gengibre": "Hortifrúti — Verduras e Legumes",
  "hortela": "Hortifrúti — Verduras e Legumes",
  "salsinha": "Hortifrúti — Verduras e Legumes",
  "coentro": "Hortifrúti — Verduras e Legumes",
  "milhoverdeespiga": "Hortifrúti — Verduras e Legumes",
  "cebola": "Hortifrúti — Verduras e Legumes",

  // ─── Hortifrúti — Frutas ───
  "bananananica": "Hortifrúti — Frutas",
  "bananaprata": "Hortifrúti — Frutas",
  "macagalafuji": "Hortifrúti — Frutas",
  "pera": "Hortifrúti — Frutas",
  "uvathompson": "Hortifrúti — Frutas",
  "laranjapera": "Hortifrúti — Frutas",
  "limaotahiti": "Hortifrúti — Frutas",
  "limaosiciliano": "Hortifrúti — Frutas",
  "mamaopapaya": "Hortifrúti — Frutas",
  "melancia": "Hortifrúti — Frutas",
  "melao": "Hortifrúti — Frutas",
  "abacaxi": "Hortifrúti — Frutas",
  "mangatommy": "Hortifrúti — Frutas",
  "maracuja": "Hortifrúti — Frutas",
  "morango": "Hortifrúti — Frutas",
  "acerola": "Hortifrúti — Frutas",
  "cocoverde": "Hortifrúti — Frutas",
  "cocosecoralado": "Hortifrúti — Frutas",
  "goiaba": "Hortifrúti — Frutas",
  "jabuticaba": "Hortifrúti — Frutas",
  "abacate": "Hortifrúti — Frutas",
  "kiwi": "Hortifrúti — Frutas",
  "mamaoformosa": "Hortifrúti — Frutas",
  "coco": "Hortifrúti — Frutas",

  // ─── Grãos e Cereais ───
  "arroz": "Grãos e Cereais",
  "arrozbrancotipo1": "Grãos e Cereais",
  "arrozintegral": "Grãos e Cereais",
  "arrozarboreo": "Grãos e Cereais",
  "arrozparboilizado": "Grãos e Cereais",
  "feijao": "Grãos e Cereais",
  "feijaopreto": "Grãos e Cereais",
  "feijaocarioca": "Grãos e Cereais",
  "feijaofradinho": "Grãos e Cereais",
  "feijaobranco": "Grãos e Cereais",
  "lentilha": "Grãos e Cereais",
  "graodebico": "Grãos e Cereais",
  "ervilhaseca": "Grãos e Cereais",
  "sojagrao": "Grãos e Cereais",
  "milhodepipoca": "Grãos e Cereais",
  "milhoverdelata": "Grãos e Cereais",
  "aveiaemflocos": "Grãos e Cereais",
  "granola": "Grãos e Cereais",
  "farinhadetrigo": "Grãos e Cereais",
  "farinhademandioca": "Grãos e Cereais",
  "farinhaderosca": "Grãos e Cereais",
  "fuba": "Grãos e Cereais",
  "polvilhodoce": "Grãos e Cereais",
  "polvilhoazedo": "Grãos e Cereais",
  "amidodemilho": "Grãos e Cereais",
  "farinhadearroz": "Grãos e Cereais",
  "quinoa": "Grãos e Cereais",
  "farinha": "Grãos e Cereais",
  "acucar": "Grãos e Cereais",
  "farinhalactea": "Grãos e Cereais",

  // ─── Massas ───
  "espaguete500g": "Massas",
  "penne500g": "Massas",
  "fusilli500g": "Massas",
  "farfalle500g": "Massas",
  "talharim500g": "Massas",
  "lasanha500g": "Massas",
  "nhoque500g": "Massas",
  "raviolidecarne": "Massas",
  "capeletti": "Massas",
  "canelone": "Massas",
  "macarraosopinha": "Massas",
  "massaparapastel": "Massas",
  "massadepizza": "Massas",
  "massadepaodequeijo": "Massas",
  "macarrao": "Massas",

  // ─── Padaria e Confeitaria ───
  "pao": "Padaria e Confeitaria",
  "paofrances": "Padaria e Confeitaria",
  "paodeformabranco": "Padaria e Confeitaria",
  "paodeformaintegral": "Padaria e Confeitaria",
  "paodeleite": "Padaria e Confeitaria",
  "baguete": "Padaria e Confeitaria",
  "ciabatta": "Padaria e Confeitaria",
  "paoaustraliano": "Padaria e Confeitaria",
  "paodequeijo": "Padaria e Confeitaria",
  "paosirio": "Padaria e Confeitaria",
  "paobrioche": "Padaria e Confeitaria",
  "croissant": "Padaria e Confeitaria",
  "bolodechocolate": "Padaria e Confeitaria",
  "bolodecenoura": "Padaria e Confeitaria",
  "bolodelaranja": "Padaria e Confeitaria",
  "bolodefuba": "Padaria e Confeitaria",
  "tortaholandesa": "Padaria e Confeitaria",
  "tortadelimao": "Padaria e Confeitaria",
  "pudim": "Padaria e Confeitaria",
  "sonhodocesfolhados": "Padaria e Confeitaria",
  "paodemel": "Padaria e Confeitaria",
  "torrada": "Padaria e Confeitaria",
  "paodealho": "Padaria e Confeitaria",

  // ─── Biscoitos e Snacks ───
  "biscoito": "Biscoitos e Snacks",
  "biscoitocreamcracker": "Biscoitos e Snacks",
  "biscoitomaizena": "Biscoitos e Snacks",
  "biscoitoaguasal": "Biscoitos e Snacks",
  "biscoitorecheado": "Biscoitos e Snacks",
  "bolacha": "Biscoitos e Snacks",
  "bolacharecheada": "Biscoitos e Snacks",
  "salgadinho": "Biscoitos e Snacks",
  "batatachips": "Biscoitos e Snacks",
  "batatapalha": "Biscoitos e Snacks",
  "amendoim": "Biscoitos e Snacks",
  "castanha": "Biscoitos e Snacks",
  "castanhadecaju": "Biscoitos e Snacks",
  "castanhadoBrasil": "Biscoitos e Snacks",
  "barrinhadecereal": "Biscoitos e Snacks",
  "pipoca": "Biscoitos e Snacks",
  "milhopipoca": "Biscoitos e Snacks",

  // ─── Molhos e Condimentos ───
  "azeite": "Molhos e Condimentos",
  "molhodetomatetradicional": "Molhos e Condimentos",
  "extratodetomate": "Molhos e Condimentos",
  "tomatepelado": "Molhos e Condimentos",
  "catchup": "Molhos e Condimentos",
  "mostardaamarela": "Molhos e Condimentos",
  "mostardadijon": "Molhos e Condimentos",
  "maionese": "Molhos e Condimentos",
  "shoyumolhodesoja": "Molhos e Condimentos",
  "molhoingles": "Molhos e Condimentos",
  "molhobarbecue": "Molhos e Condimentos",
  "molhopimenta": "Molhos e Condimentos",
  "vinagredealcool": "Molhos e Condimentos",
  "vinagredemaca": "Molhos e Condimentos",
  "vinagrebalsamico": "Molhos e Condimentos",
  "azeitedeolivaextravirgem": "Molhos e Condimentos",
  "azeitedeolivagalao": "Molhos e Condimentos",
  "azeitededende": "Molhos e Condimentos",
  "molhobrancopronto": "Molhos e Condimentos",
  "molhomadeira": "Molhos e Condimentos",
  "molhorose": "Molhos e Condimentos",
  "molhodealho": "Molhos e Condimentos",
  "maionesetemperada": "Molhos e Condimentos",
  "molho": "Molhos e Condimentos",

  // ─── Temperos e Especiarias ───
  "sal": "Temperos e Especiarias",
  "salrefinado": "Temperos e Especiarias",
  "salgrosso": "Temperos e Especiarias",
  "salmarinho": "Temperos e Especiarias",
  "pimentadoreinomoida": "Temperos e Especiarias",
  "pimentadoreinoemgraos": "Temperos e Especiarias",
  "pimentacalabresa": "Temperos e Especiarias",
  "pimentamalagueta": "Temperos e Especiarias",
  "cominho": "Temperos e Especiarias",
  "oregano": "Temperos e Especiarias",
  "manjericaodesidratado": "Temperos e Especiarias",
  "alecrimdesidratado": "Temperos e Especiarias",
  "tomilho": "Temperos e Especiarias",
  "lourofolha": "Temperos e Especiarias",
  "colorau": "Temperos e Especiarias",
  "acafraoempo": "Temperos e Especiarias",
  "curry": "Temperos e Especiarias",
  "papricadoce": "Temperos e Especiarias",
  "papricadefumada": "Temperos e Especiarias",
  "nozmoscada": "Temperos e Especiarias",
  "canelaempo": "Temperos e Especiarias",
  "cravodaindia": "Temperos e Especiarias",
  "alhoempo": "Temperos e Especiarias",
  "cebolaempo": "Temperos e Especiarias",
  "caldodegalinhacubo": "Temperos e Especiarias",
  "caldodecarnecubo": "Temperos e Especiarias",
  "caldodelegumescubo": "Temperos e Especiarias",
  "temperocompletoalhoesal": "Temperos e Especiarias",
  "essenciadebaunilha": "Temperos e Especiarias",
  "tempero": "Temperos e Especiarias",

  // ─── Óleos e Gorduras ───
  "oleo": "Óleos e Gorduras",
  "oleodesojagalao900ml": "Óleos e Gorduras",
  "oleodesojagalao3l": "Óleos e Gorduras",
  "oleodecanola": "Óleos e Gorduras",
  "oleodemilho": "Óleos e Gorduras",
  "oleodegergelim": "Óleos e Gorduras",
  "banhadeporco": "Óleos e Gorduras",
  "gorduravegetalhidrogenada": "Óleos e Gorduras",
  "manteigaclarificadaghee": "Óleos e Gorduras",
  "sprayantiaderente": "Óleos e Gorduras",
  "oleodecoco": "Óleos e Gorduras",

  // ─── Enlatados e Conservas ───
  "atumsolidoemoleo": "Enlatados e Conservas",
  "sardinhaemoleo": "Enlatados e Conservas",
  "milhoverdeemlata": "Enlatados e Conservas",
  "ervilhaemlata": "Enlatados e Conservas",
  "seletadelegumes": "Enlatados e Conservas",
  "palmito": "Enlatados e Conservas",
  "azeitonaverde": "Enlatados e Conservas",
  "azeitonapreta": "Enlatados e Conservas",
  "cogumeloparis": "Enlatados e Conservas",
  "cogumeloshitake": "Enlatados e Conservas",
  "alcachofra": "Enlatados e Conservas",
  "pimentabiquinho": "Enlatados e Conservas",
  "cebolaemconserva": "Enlatados e Conservas",
  "salsichaemlata": "Enlatados e Conservas",
  "patedefigado": "Enlatados e Conservas",
  "patedeazeitona": "Enlatados e Conservas",

  // ─── Bebidas Não Alcoólicas ───
  "cafe": "Bebidas Não Alcoólicas",
  "cocacolalata350ml": "Bebidas Não Alcoólicas",
  "cocacola600ml": "Bebidas Não Alcoólicas",
  "cocacola2l": "Bebidas Não Alcoólicas",
  "guaranaantarcticalata": "Bebidas Não Alcoólicas",
  "guaranaantarctica2l": "Bebidas Não Alcoólicas",
  "spritelata": "Bebidas Não Alcoólicas",
  "fantalaranjalata": "Bebidas Não Alcoólicas",
  "fantauvalata": "Bebidas Não Alcoólicas",
  "pepsilata": "Bebidas Não Alcoólicas",
  "sucodelaranjacaixa1l": "Bebidas Não Alcoólicas",
  "sucodeuvacaixa1l": "Bebidas Não Alcoólicas",
  "sucodemaracujacaixa1l": "Bebidas Não Alcoólicas",
  "sucodetoxverde": "Bebidas Não Alcoólicas",
  "aguamineralsgas500ml": "Bebidas Não Alcoólicas",
  "aguamineralsgas15l": "Bebidas Não Alcoólicas",
  "aguamineralcgas500ml": "Bebidas Não Alcoólicas",
  "aguadecococaixa1l": "Bebidas Não Alcoólicas",
  "cafeempo500g": "Bebidas Não Alcoólicas",
  "cafesoluvelgranulado": "Bebidas Não Alcoólicas",
  "capsuladecafe": "Bebidas Não Alcoólicas",
  "chocolateempo500g": "Bebidas Não Alcoólicas",
  "achocolatado400g": "Bebidas Não Alcoólicas",
  "chamatecaixinha": "Bebidas Não Alcoólicas",
  "chacamomilasache": "Bebidas Não Alcoólicas",
  "chahortelasache": "Bebidas Não Alcoólicas",
  "energeticolata250ml": "Bebidas Não Alcoólicas",
  "h2olata": "Bebidas Não Alcoólicas",
  "gatoradelata": "Bebidas Não Alcoólicas",
  "agua": "Bebidas Não Alcoólicas",
  "suco": "Bebidas Não Alcoólicas",
  "refri": "Bebidas Não Alcoólicas",
  "achocolatado": "Bebidas Não Alcoólicas",
  "polpa": "Bebidas Não Alcoólicas",
  "gelo": "Bebidas Não Alcoólicas",
  "leitedecoco": "Bebidas Não Alcoólicas",

  // ─── Bebidas Alcoólicas ───
  "cerveja": "Bebidas Alcoólicas",
  "skollata350ml": "Bebidas Alcoólicas",
  "brahmalata350ml": "Bebidas Alcoólicas",
  "antarcticalata350ml": "Bebidas Alcoólicas",
  "heinekenlongneck330ml": "Bebidas Alcoólicas",
  "heinekenlata350ml": "Bebidas Alcoólicas",
  "stellaartoislongneck": "Bebidas Alcoólicas",
  "coronalongneck": "Bebidas Alcoólicas",
  "budweiserlata": "Bebidas Alcoólicas",
  "amstellata": "Bebidas Alcoólicas",
  "choppartesanalcopo": "Bebidas Alcoólicas",
  "cervejaembarril30l": "Bebidas Alcoólicas",
  "vinhotintoseco": "Bebidas Alcoólicas",
  "vinhobrancoseco": "Bebidas Alcoólicas",
  "vinhorose": "Bebidas Alcoólicas",
  "espumantebrut": "Bebidas Alcoólicas",
  "espumantemoscatel": "Bebidas Alcoólicas",
  "whiskygarrafa": "Bebidas Alcoólicas",
  "vodkagarrafa": "Bebidas Alcoólicas",
  "cachacagarrafa": "Bebidas Alcoólicas",
  "gingarrafa": "Bebidas Alcoólicas",
  "rumgarrafa": "Bebidas Alcoólicas",
  "tequilagarrafa": "Bebidas Alcoólicas",
  "conhaque": "Bebidas Alcoólicas",
  "licordiversos": "Bebidas Alcoólicas",
  "vermute": "Bebidas Alcoólicas",
  "catuaba": "Bebidas Alcoólicas",
  "alcooldecereaisgarrafa": "Bebidas Alcoólicas",

  // ─── Descartáveis ───
  "copodescartavel200mlagua": "Descartáveis",
  "copodescartavel50mlcafe": "Descartáveis",
  "copoplastico300mlchopp": "Descartáveis",
  "pratodescartavel": "Descartáveis",
  "talherdescartavelkit": "Descartáveis",
  "guardanapodepapel": "Descartáveis",
  "toalhadepapel": "Descartáveis",
  "papeltoalhainterfolhado": "Descartáveis",
  "canudoplastico": "Descartáveis",
  "tampaparacopodescartavel": "Descartáveis",
  "filmepvcrolo": "Descartáveis",
  "papelaluminiorolo": "Descartáveis",
  "papelmanteiga": "Descartáveis",
  "luvadescartavelcaixa": "Descartáveis",
  "toucadescartavel": "Descartáveis",
  "sacodelixo30l": "Descartáveis",
  "sacodelixo50l": "Descartáveis",
  "sacodelixo100l": "Descartáveis",
  "mascaradescartavel": "Descartáveis",

  // ─── Material de Limpeza ───
  "detergenteliquido500ml": "Material de Limpeza",
  "sabaoliquidoparaloucas": "Material de Limpeza",
  "sabaoempo1kg": "Material de Limpeza",
  "desinfetante500ml": "Material de Limpeza",
  "aguasanitaria1l": "Material de Limpeza",
  "alcool701l": "Material de Limpeza",
  "limpavidros500ml": "Material de Limpeza",
  "limpamultiuso500ml": "Material de Limpeza",
  "lustramoveis": "Material de Limpeza",
  "desengordurante500ml": "Material de Limpeza",
  "limpafornos": "Material de Limpeza",
  "saponaceopo": "Material de Limpeza",
  "esponjaduplaface": "Material de Limpeza",
  "esponjadeacopalhadeaco": "Material de Limpeza",
  "panodechaounidade": "Material de Limpeza",
  "panodecopamicrofibra": "Material de Limpeza",
  "rodinho": "Material de Limpeza",
  "balde": "Material de Limpeza",
  "amaciante1l": "Material de Limpeza",
  "inseticidaspray": "Material de Limpeza",
  "sabao": "Material de Limpeza",
  "detergente": "Material de Limpeza",
  "amaciante": "Material de Limpeza",

  // ─── Utensílios e Equipamentos ───
  "facachefaco": "Utensílios e Equipamentos",
  "facadepao": "Utensílios e Equipamentos",
  "facadelegumes": "Utensílios e Equipamentos",
  "facaparacarnecefiladeira": "Utensílios e Equipamentos",
  "tabuadecortepolietileno": "Utensílios e Equipamentos",
  "paneladepressao7l": "Utensílios e Equipamentos",
  "panelaaltainox": "Utensílios e Equipamentos",
  "frigideiraantiaderente": "Utensílios e Equipamentos",
  "assadeiraretangular": "Utensílios e Equipamentos",
  "formadebolo": "Utensílios e Equipamentos",
  "colherdepau": "Utensílios e Equipamentos",
  "espatuladesilicone": "Utensílios e Equipamentos",
  "concha": "Utensílios e Equipamentos",
  "escorredordemacarrao": "Utensílios e Equipamentos",
  "liquidificadorindustrial": "Utensílios e Equipamentos",
  "batedeiraplanetaria": "Utensílios e Equipamentos",
  "processadordealimentos": "Utensílios e Equipamentos",
  "balancadigital5kg": "Utensílios e Equipamentos",
  "balancadigital15kg": "Utensílios e Equipamentos",
  "termometroculinario": "Utensílios e Equipamentos",
  "medidorxicaracolher": "Utensílios e Equipamentos",
  "ralador": "Utensílios e Equipamentos",
  "descascadordelegumes": "Utensílios e Equipamentos",
  "peneira": "Utensílios e Equipamentos",
  "coadordecafe": "Utensílios e Equipamentos",

  // ─── EPIs ───
  "luvadeprocedimentocaixa": "EPIs",
  "luvatermicaforno": "EPIs",
  "luvademalhaaco": "EPIs",
  "toucadescartavelpacote": "EPIs",
  "aventalbrancolongo": "EPIs",
  "aventalimpermeavel": "EPIs",
  "mascaradescartavelcaixa": "EPIs",
  "oculosdeprotecao": "EPIs",
  "sapatofechadoantiderrapante": "EPIs",
  "botadeborracha": "EPIs",
  "protetorauricular": "EPIs",
  "rededeprotecaocabelo": "EPIs",
  "capadechuvaimpermeavel": "EPIs",

  // ─── Embalagens ───
  "marmitexaluminio700ml": "Embalagens",
  "marmitexaluminio500ml": "Embalagens",
  "tampaparamarmitex": "Embalagens",
  "poteplastico500ml": "Embalagens",
  "poteplastico1l": "Embalagens",
  "sacoplastico20x30": "Embalagens",
  "sacoplastico30x45": "Embalagens",
  "sacoavacuo": "Embalagens",
  "papelkraftfolha": "Embalagens",
  "sacodepapellanche": "Embalagens",
  "caixadepizzamedia": "Embalagens",
  "caixadepizzagrande": "Embalagens",
  "embalagemparadeliverysaco": "Embalagens",
  "adesivodeselagem": "Embalagens",
  "fitacrepe": "Embalagens",
  "caixadepapelaopequena": "Embalagens",
  "caixadepapelaomedia": "Embalagens",
  "caixadepapelaogrande": "Embalagens",
  "barbanterolo": "Embalagens",
  "elasticodeamarrar": "Embalagens",
};
