// Default admin settings keys
export const ADMIN_SETTINGS_KEYS = [
  // Notifications
  "alert_sound_enabled",
  "alert_sound_type",
  "alert_sound_volume",
  "alert_expiry_days",
  "alert_expiry_same_day",
  "alert_expiry_day_before",
  "alert_low_stock_pct",
  "alert_critical_stock_pct",
  "alert_check_interval_minutes",

  // Stock & Purchasing
  "stock_lead_time_days",
  "stock_consumption_days",
  "stock_safety_margin_pct",

  // Financial
  "financial_cmv_target_min",
  "financial_cmv_target_max",
  "financial_closing_day",

  // System
  "system_dashboard_period",
  "system_language",
  "system_date_format",
  "system_time_format",
  "system_decimal_places",

  // Security
  "security_password_expiry_days",
] as const;

export const DEFAULT_SETTINGS: Record<string, string> = {
  alert_sound_enabled: "true",
  alert_sound_type: "beep",
  alert_sound_volume: "50",
  alert_expiry_days: "7",
  alert_expiry_same_day: "true",
  alert_expiry_day_before: "true",
  alert_low_stock_pct: "10",
  alert_critical_stock_pct: "5",
  alert_check_interval_minutes: "5",
  stock_lead_time_days: "7",
  stock_consumption_days: "30",
  stock_safety_margin_pct: "20",
  financial_cmv_target_min: "28",
  financial_cmv_target_max: "35",
  financial_closing_day: "1",
  system_dashboard_period: "30",
  system_language: "pt-BR",
  system_date_format: "DD/MM/AAAA",
  system_time_format: "24h",
  system_decimal_places: "2",
  security_password_expiry_days: "0",
};

export const SETTING_LABELS: Record<string, string> = {
  alert_sound_enabled: "Alerta Sonoro",
  alert_sound_type: "Tipo de Som",
  alert_sound_volume: "Volume do Alerta",
  alert_expiry_days: "Dias de Antecedência (Vencimento)",
  alert_expiry_same_day: "Notificar no Dia do Vencimento",
  alert_expiry_day_before: "Notificar 1 Dia Antes",
  alert_low_stock_pct: "Percentual Estoque Baixo",
  alert_critical_stock_pct: "Percentual Estoque Crítico",
  alert_check_interval_minutes: "Intervalo de Verificação",
  stock_lead_time_days: "Lead Time Padrão (dias)",
  stock_consumption_days: "Base de Consumo (dias)",
  stock_safety_margin_pct: "Margem de Segurança (%)",
  financial_cmv_target_min: "Meta CMV Mínima (%)",
  financial_cmv_target_max: "Meta CMV Máxima (%)",
  financial_closing_day: "Dia de Fechamento Mensal",
  system_dashboard_period: "Período Padrão do Dashboard",
  system_language: "Idioma",
  system_date_format: "Formato de Data",
  system_time_format: "Formato de Hora",
  system_decimal_places: "Casas Decimais",
  security_password_expiry_days: "Expiração de Senha (dias)",
};

export const SETTING_DESCRIPTIONS: Record<string, string> = {
  alert_sound_enabled: "Ativar som ao receber notificações críticas ou alertas.",
  alert_sound_type: "Tipo de som: beep simples, alarme ou nenhum.",
  alert_sound_volume: "Volume do som de notificação (0 a 100).",
  alert_expiry_days: "Com quantos dias de antecedência alertar sobre vencimentos.",
  alert_expiry_same_day: "Notificar quando o item vencer no dia atual.",
  alert_expiry_day_before: "Notificar 1 dia antes do vencimento.",
  alert_low_stock_pct: "Percentual acima do mínimo para considerar estoque baixo.",
  alert_critical_stock_pct: "Percentual acima do mínimo para considerar estoque crítico.",
  alert_check_interval_minutes: "Intervalo entre verificações de notificações (minutos).",
  stock_lead_time_days: "Prazo médio de entrega dos fornecedores (usado na sugestão de compra).",
  stock_consumption_days: "Quantos dias de histórico usar para calcular consumo médio.",
  stock_safety_margin_pct: "Percentual extra adicionado na sugestão de compra.",
  financial_cmv_target_min: "Meta inferior de CMV para alertas.",
  financial_cmv_target_max: "Meta superior de CMV para alertas.",
  financial_closing_day: "Dia do mês para fechamento financeiro.",
  system_dashboard_period: "Período inicial do dashboard (dias).",
  system_language: "Idioma do sistema (português é o padrão).",
  system_date_format: "Formato de exibição de datas no sistema.",
  system_time_format: "Formato de exibição de horas (24h ou 12h AM/PM).",
  system_decimal_places: "Número de casas decimais para valores financeiros.",
  security_password_expiry_days: "Obrigar troca de senha a cada X dias. 0 = nunca.",
};

export const SETTING_CATEGORIES: Record<string, string> = {
  alert_sound_enabled: "notifications",
  alert_sound_type: "notifications",
  alert_sound_volume: "notifications",
  alert_expiry_days: "notifications",
  alert_expiry_same_day: "notifications",
  alert_expiry_day_before: "notifications",
  alert_low_stock_pct: "notifications",
  alert_critical_stock_pct: "notifications",
  alert_check_interval_minutes: "notifications",
  stock_lead_time_days: "stock",
  stock_consumption_days: "stock",
  stock_safety_margin_pct: "stock",
  financial_cmv_target_min: "financial",
  financial_cmv_target_max: "financial",
  financial_closing_day: "financial",
  system_dashboard_period: "system",
  system_language: "system",
  system_date_format: "system",
  system_time_format: "system",
  system_decimal_places: "system",
  security_password_expiry_days: "system",
};

export const SETTING_TYPES: Record<string, "number" | "boolean" | "select" | "text"> = {
  alert_sound_enabled: "boolean",
  alert_sound_type: "select",
  alert_sound_volume: "number",
  alert_expiry_days: "number",
  alert_expiry_same_day: "boolean",
  alert_expiry_day_before: "boolean",
  alert_low_stock_pct: "number",
  alert_critical_stock_pct: "number",
  alert_check_interval_minutes: "number",
  stock_lead_time_days: "number",
  stock_consumption_days: "number",
  stock_safety_margin_pct: "number",
  financial_cmv_target_min: "number",
  financial_cmv_target_max: "number",
  financial_closing_day: "number",
  system_dashboard_period: "number",
  system_language: "select",
  system_date_format: "select",
  system_time_format: "select",
  system_decimal_places: "select",
  security_password_expiry_days: "select",
};

export const SETTING_OPTIONS: Record<string, { label: string; value: string }[]> = {
  alert_sound_type: [
    { label: "Beep", value: "beep" },
    { label: "Alarme", value: "alarm" },
    { label: "Nenhum", value: "none" },
  ],
  alert_check_interval_minutes: [
    { label: "1 minuto", value: "1" },
    { label: "5 minutos", value: "5" },
    { label: "15 minutos", value: "15" },
    { label: "30 minutos", value: "30" },
    { label: "60 minutos", value: "60" },
  ],
  stock_consumption_days: [
    { label: "30 dias", value: "30" },
    { label: "60 dias", value: "60" },
    { label: "90 dias", value: "90" },
  ],
  system_dashboard_period: [
    { label: "7 dias", value: "7" },
    { label: "30 dias", value: "30" },
    { label: "90 dias", value: "90" },
    { label: "Este ano", value: "365" },
  ],
  system_language: [{ label: "Português (Brasil)", value: "pt-BR" }],
  system_date_format: [
    { label: "DD/MM/AAAA", value: "DD/MM/AAAA" },
    { label: "MM/DD/AAAA", value: "MM/DD/AAAA" },
    { label: "AAAA-MM-DD", value: "AAAA-MM-DD" },
  ],
  system_time_format: [
    { label: "24h (14:30)", value: "24h" },
    { label: "12h (02:30 PM)", value: "12h" },
  ],
  system_decimal_places: [
    { label: "0 casas", value: "0" },
    { label: "1 casa", value: "1" },
    { label: "2 casas", value: "2" },
  ],
  security_password_expiry_days: [
    { label: "Nunca", value: "0" },
    { label: "30 dias", value: "30" },
    { label: "60 dias", value: "60" },
    { label: "90 dias", value: "90" },
  ],
};
